[Distribution]
Distribution=debian
Release=trixie

[Output]
Format=tar
CompressOutput=xz
Output=image

[Build]
WithNetwork=true

[Content]
Bootable=no
Packages=
    apt
    bash
    ca-certificates
    dbus
    systemd
    unattended-upgrades
