[Distribution]
Distribution=debian
Release=trixie

[Output]
Format=tar
CompressOutput=xz
Output=image

[Build]
# Use bundled build tools instead of host tools
ToolsTree=yes
# Run build and postinst scripts with network access
WithNetwork=true

[Content]
# Enables or disables generation of a bootable image
Bootable=no
# Remove package manager database and other files
CleanPackageMetadata=yes
Packages=
    apt
    bash
    ca-certificates
    dbus
    systemd
    unattended-upgrades
